export const gems = [
    {
        id: 'itemAmethyst',
        name: 'Amethyst',
        image: '../assets/amethyst.PNG',
        description: 'Purple',
        category: 'Aquarius',
        price: '$75',
    },
    {
        id: 'itemEmerald',
        name: 'Emerald',
        image: '../assets/emerald.PNG',
        description: 'Green',
        category: 'Taurus',
        price: '$100',
    },
    {
        id: 'itemMoonstone',
        name: 'Moonstone',
        image: '../assets/moonstone.PNG',
        description: 'Turquoise',
        category: 'Gemini',
        price: '$75',
    },
    {
        id: 'itemRuby',
        name: 'Ruby',
        image: '../assets/ruby.PNG',
        description: 'Red',
        category: 'Cancer',
        price: '$100',
    },
    {
        id: 'itemSapphire',
        name: 'Sapphire',
        image: '../assets/sapphire.PNG',
        description: 'Blue',
        category: 'Virgo',
        price: '$100',
    },
    {
        id: 'itemTopaz',
        name: 'Topaz',
        image: '../assets/topaz.PNG',
        description: 'Gold',
        category: 'Scorpio',
        price: '$100',
    },
];