export const gems = [
    {
        id: 'itemAmethyst',
        name: 'Amethyst',
        image: '',
        description: 'Purple',
        category: 'Aquarius',
        price: '75',
    },
    {
        id: 'itemEmerald',
        name: 'Emerald',
        image: '',
        description: 'Green',
        category: 'Taurus',
        price: '100',
    },
    {
        id: 'itemMoonstone',
        name: 'Moonstone',
        image: '',
        description: 'Blue/Green',
        category: 'Gemini',
        price: '75',
    },
    {
        id: 'itemRuby',
        name: 'Ruby',
        image: '',
        description: 'Red',
        category: 'Cancer',
        price: '100',
    },
    {
        id: 'itemSapphire',
        name: 'Sapphire',
        image: '',
        description: 'Blue',
        category: 'Virgo',
        price: '100',
    },
    {
        id: 'itemTopaz',
        name: 'Topaz',
        image: '',
        description: 'Yellow',
        category: 'Scorpio',
        price: '100',
    },
];